Feature/org structure
moongrail/caselab-edm pull request #117
Opened 2024-11-17 13:37 UTC by nof-ceo

2024-11-17 13:50 UTC, ryzendee approved these changes

2024-11-18 07:56 UTC, larentiina requested changes

2024-11-18 07:56 UTC, larentiina commented on backend/src/main/java/ru/caselab/edm/backend/service/impl/DepartmentServiceImpl.java
>      public DepartmentDTO createDepartment(CreateDepartmentDTO createDepartmentDTO) {
Не увидела логики. Если департамент, который мы создаём - родитель других департаментов, то менеджеры департаментов - потомков, также назначаются участниками департамента родителя

2024-11-20 09:07 UTC, 1shukhrat approved these changes

2024-11-20 15:30 UTC, larentiina approved these changes

2024-11-20 15:44 UTC, merged