Backend nof
moongrail/caselab-edm pull request #2
Opened 2024-10-07 18:04 UTC by nof-ceo

2024-10-07 18:27 UTC, moongrail commented on .DS_Store
И вот этот файл удали

2024-10-07 18:39 UTC, moongrail approved these changes

2024-10-08 05:09 UTC, ryzendee commented on backend/src/main/java/ru/caselab/edm/backend/entity/User.java
> +@Data
У тебя на обеих сущностях стоит `@Data`, возможно что из-за equals/hashcode и toString будут запросы в БД и рекурсивные вызовы (User.toString достанет List, далее будут вызовы Role.toString, Role.toString вновь вызовет User.toString и так по кругу, с equals и hashcode то же самое)

2024-10-08 18:58 UTC, larentiina requested changes

2024-10-08 18:58 UTC, larentiina commented on backend/src/main/java/ru/caselab/edm/backend/entity/Document.java
> +}
Зачем тут этот класс? Если он в твоём коде даже в роли заглушки не используется

2024-10-08 18:58 UTC, larentiina commented on backend/src/main/java/ru/caselab/edm/backend/service/impl/JwtServiceImpl.java
> +                .setExpiration(new Date(System.currentTimeMillis() + (30L * 24 * 60 * 60 * 100000)))
Магические числа - лучше в константу вынести

2024-10-08 18:58 UTC, larentiina commented on backend/src/main/java/ru/caselab/edm/backend/entity/Role.java
> +    @Column(name = "name")
добавить в Column -unique и nullable

2024-10-08 18:58 UTC, larentiina commented on backend/src/main/java/ru/caselab/edm/backend/service/impl/UserServiceImpl.java
> +            userRepository.save(exisingUser);
лучше добавить проверку, что поля в  updatedUser не null и только после проверки устанавливать новые значения в user

2024-10-08 19:58 UTC, nof-ceo commented on backend/src/main/java/ru/caselab/edm/backend/entity/Document.java
> +}
он был в классе у Шухрата, чтобы компилировалось пришлось так сделать

2024-10-08 20:00 UTC, larentiina commented on backend/src/main/java/ru/caselab/edm/backend/entity/Document.java
> +}
Поняла

2024-10-08 20:04 UTC, larentiina approved these changes

2024-10-09 09:25 UTC, merged